### ISSUE TITLE
Fix challenge date issue

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc#40]
I get the following error using either the documentation UI or the client. The issue happens only when I'm running the server in development mode. The issue does not occur when running the dockerized API service.

Error returned by the client:

```
$ python push_challenges.py
Traceback (most recent call last):
  File "push_challenges.py", line 146, in <module>
    main()
  File "push_challenges.py", line 142, in main
    populate_db(api_client, json_dump)
  File "push_challenges.py", line 128, in populate_db
    add_challenge(challenge_api, challenge, person_ids)
  File "push_challenges.py", line 95, in add_challenge
    api.create_challenge(challenge=challenge)
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api/challenge_api.py", line 68, in create_challenge
    return self.create_challenge_with_http_info(challenge, **kwargs)  # noqa: E501
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api/challenge_api.py", line 158, in create_challenge_with_http_info
    return self.api_client.call_api(
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api_client.py", line 373, in call_api
    return self.__call_api(resource_path, method,
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api_client.py", line 192, in __call_api
    raise e
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api_client.py", line 185, in __call_api
    response_data = self.request(
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api_client.py", line 417, in request
    return self.rest_client.POST(url,
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/rest.py", line 266, in POST
    return self.request("POST", url,
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/rest.py", line 225, in request
    raise ApiException(http_resp=r)
roccclient.exceptions.ApiException: (500)
Reason: INTERNAL SERVER ERROR
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '122', 'Server': 'Werkzeug/1.0.1 Python/3.8.5', 'Date': 'Fri, 18 Dec 2020 04:37:18 GMT'})
HTTP response body: {
  "detail": "Parser must be a string or character stream, not datetime",
  "status": 500,
  "title": "Internal error"
}
```

Response from the API server:

```
...
127.0.0.1 - - [17/Dec/2020 20:37:18] "POST /api/v1/persons HTTP/1.1" 200 -
127.0.0.1 - - [17/Dec/2020 20:37:18] "POST /api/v1/persons HTTP/1.1" 200 -
127.0.0.1 - - [17/Dec/2020 20:37:18] "POST /api/v1/persons HTTP/1.1" 200 -
127.0.0.1 - - [17/Dec/2020 20:37:18] "POST /api/v1/persons HTTP/1.1" 200 -
127.0.0.1 - - [17/Dec/2020 20:37:18] "POST /api/v1/persons HTTP/1.1" 200 -
127.0.0.1 - - [17/Dec/2020 20:37:18] "POST /api/v1/persons HTTP/1.1" 200 -
127.0.0.1 - - [17/Dec/2020 20:37:18] "POST /api/v1/persons HTTP/1.1" 200 -
127.0.0.1 - - [17/Dec/2020 20:37:18] "POST /api/v1/challenges HTTP/1.1" 500 -
```

Interestingly, the first challenge ends up in the DB with the dates successfully set. Yet the request returns 500.

**Comment by tschaffter** [comment]
Running the development server dockerized works, so the difference does not come from uWSGI, which I use to spin up the production server.

Using locally the same libraries as in the docker container (see below) does not solve the issue.

```
# pip freeze
pip install attrs==20.3.0 \
certifi==2020.12.5 \
chardet==3.0.4 \
click==7.1.2 \
clickclick==20.10.2 \
connexion==2.7.0 \
Flask==1.1.2 \
idna==2.10 \
inflection==0.5.1 \
itsdangerous==1.1.0 \
Jinja2==2.11.2 \
jsonschema==3.2.0 \
MarkupSafe==1.1.1 \
mongoengine==0.21.0 \
openapi-spec-validator==0.2.9 \
psycopg2-binary==2.8.6 \
pymongo==3.11.2 \
pyrsistent==0.17.3 \
PyYAML==5.3.1 \
requests==2.25.0 \
six==1.15.0 \
swagger-ui-bundle==0.0.8 \
urllib3==1.26.2 \
Werkzeug==1.0.1
```

**Comment by tschaffter** [comment]
Here is the full error thrown in the create_challenge controller function:

```
Traceback (most recent call last):
  File "/mnt/c/Users/thoma/Documents/dev/rocc/server/openapi_server/controllers/challenge_controller.py", line 61, in create_challenge
    res = Challenge.from_dict(db_challenge.to_dict())
  File "/mnt/c/Users/thoma/Documents/dev/rocc/server/openapi_server/models/challenge.py", line 85, in from_dict
    return util.deserialize_model(dikt, cls)
  File "/mnt/c/Users/thoma/Documents/dev/rocc/server/openapi_server/util.py", line 111, in deserialize_model
    setattr(instance, attr, _deserialize(value, attr_type))
  File "/mnt/c/Users/thoma/Documents/dev/rocc/server/openapi_server/util.py", line 23, in _deserialize
    return deserialize_date(data)
  File "/mnt/c/Users/thoma/Documents/dev/rocc/server/openapi_server/util.py", line 71, in deserialize_date
    return parse(string).date()
  File "/home/tschaffter/.conda/envs/rocc/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/tschaffter/.conda/envs/rocc/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/tschaffter/.conda/envs/rocc/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/tschaffter/.conda/envs/rocc/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/home/tschaffter/.conda/envs/rocc/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 75, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
```

**Comment by tschaffter** [comment]
The error described in this ticket does not occurs when using a clean environment as described in the project README.
